# Generated by Django 3.0.7 on 2020-07-09 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0002_book'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderUpdate',
        ),
    ]
