# Generated by Django 3.0.7 on 2020-07-09 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0003_auto_20200710_0010'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Book',
            new_name='FindProduct',
        ),
    ]
