# Generated by Django 3.0.7 on 2020-07-09 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0005_order_orderupdate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderUpdate',
        ),
    ]
