# Generated by Django 3.0.7 on 2020-07-09 20:07

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0007_orderupdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='findproduct',
            name='title',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Electronics', 'Electronics, Item, Amount'), ('Clothes', 'Clothes, Item, Amount')], max_length=19),
        ),
    ]
