# Generated by Django 3.0.7 on 2020-07-09 20:11

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0008_auto_20200710_0137'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelectProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Select', multiselectfield.db.fields.MultiSelectField(choices=[('Electronics', 'Electronics, Item, Amount'), ('Clothes', 'Clothes, Item, Amount')], max_length=19)),
            ],
        ),
        migrations.DeleteModel(
            name='FindProduct',
        ),
    ]
