# Generated by Django 3.0.7 on 2020-07-10 10:27

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0009_auto_20200710_0141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selectproduct',
            name='Select',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Electronics', 'Electronics'), ('Clothes', 'Clothes')], max_length=19),
        ),
    ]
