# Generated by Django 3.0.7 on 2020-07-10 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0011_remove_selectproduct_select'),
    ]

    operations = [
        migrations.AddField(
            model_name='selectproduct',
            name='category',
            field=models.CharField(default=' ', max_length=50),
        ),
        migrations.AddField(
            model_name='selectproduct',
            name='price',
            field=models.IntegerField(default=' '),
        ),
        migrations.AddField(
            model_name='selectproduct',
            name='sub_category',
            field=models.CharField(default=' ', max_length=50),
        ),
    ]
