# Generated by Django 3.0.7 on 2020-07-10 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0013_remove_selectproduct_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SelectProduct',
        ),
    ]
