# Generated by Django 3.0.7 on 2020-07-10 18:17

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0016_auto_20200710_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Electronics', 'Electronics'), ('Clothes', 'Clothes')], max_length=19),
        ),
        migrations.AlterField(
            model_name='product',
            name='sub_category',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Electronics', 'Mobile'), ('Electronics', 'TV'), ('Clothes', 'Men s clothes'), ('Clothes', 'Women s clothes')], max_length=39),
        ),
    ]
